### ISSUE TITLE
Parameter set for training over Hubble dataset

### ISSUE THREAD

**Issue by mojganaz** [stitchfix/fauxtograph#10]
Saw your Deep Style presentation and the generated images based on trained model on Hubble dataset. I was wondering what parameter set you used to train over Hubble dataset. I used the default parameter set and only got black images generated at the end! Also played with image_multiplier argument and got a bunch of similar black images with a gray (lighter) circle in the center. 
Any tips here?

**Comment by Vgandhi9** [comment]
I got the exact same error.

**Comment by tjtorres** [comment]
Sorry I've been a bit absent. I just released a big update, so if you get the new version I think you might have an easier time of training on the Hubble set. If you're noticing that all your images look the same I think you might want to try turning down the kl_ratio parameter, if it is set too high you'll underfit.
